In [1]:
import numpy as np

Use NumPy arrays instead of lists; they are coded in C and are much faster than standard Python lists

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
c = np.array([4, 5, 9, 10, 3, 14]).reshape(2, 3)
c

array([[ 4,  5,  9],
       [10,  3, 14]])

In [4]:
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

15
1
5
3.0


In [5]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
np.zeros(5) #Create an array of 0's
np.linspace(0, 6, 10) #Array of values from x to y in z even spaces
np.random.rand(3) #x random values between 0 and 1
np.random.randint(1, 1000) #Random integer between x & y
np.arange(10) #Like the range method from earlier

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])